# Generated by Django 4.1.7 on 2023-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=10),
        ),
    ]
