# Generated by Django 4.1.7 on 2023-08-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_newsletter_subscriber_delete_bag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
